import type { Metadata } from "next";
import { DM_Sans, Roboto } from "next/font/google";
import "../globals.css";
import { QueryProviders } from "../_Providers/QueryProviders";
import { CardProvider } from "../_Providers/CardProviders";
import MainLayout from "../_features/Layout/MainLayout";

// Sadece kullanılan fontları import et
const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} antialiased`}>
        <QueryProviders>
          <CardProvider>
            <MainLayout>{children}</MainLayout>
          </CardProvider>
        </QueryProviders>
      </body>
    </html>
  );
}
