import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { QueryProviders } from "../Providers/QueryProviders";
// import { CardProvider } from "../Providers/CardProviders";
import MainLayout from "../features/Layout/MainLayout";
import { CardProvider } from "../Providers/CardProviders";
import {Roboto} from "next/font/google";
import { DM_Sans } from "next/font/google";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${dmSans.variable} antialiased`}
      >
        <QueryProviders>
          <CardProvider>
            <MainLayout>
                          {children}

            </MainLayout>
          </CardProvider>
        </QueryProviders>
        
      </body>
    </html>
  );
}